"""Shared input validation helpers for API routers."""

from __future__ import annotations

import re

from fastapi import HTTPException

# Block names are 6-hex-digit strings generated by secrets.token_hex(3).
# Allow alphanumeric plus hyphens and underscores for forward compatibility.
_SAFE_NAME_RE = re.compile(r"^[a-zA-Z0-9_-]+$")


def validate_block_name(name: str) -> str:
    """Validate a block name from a URL path parameter.

    Rejects path traversal attempts, empty strings, and names with
    characters that could resolve outside expected directories.

    Returns the name unchanged if valid. Raises HTTPException(400) if not.
    """
    if not name or not _SAFE_NAME_RE.match(name):
        raise HTTPException(400, "Invalid block name")
    return name
